#!/usr/bin/env bash

set -euo pipefail

src_prefix=archive/www.goldenbandra.com/

IFS=$'\n'
files=($(cd "$src_prefix"; find -name '*.htm*'))

for f in  "${files[@]}"; do
    mkdir -p rebuild/"$(dirname $f)"
    echo "$f"
    pandoc -f html -t markdown "$src_prefix"/"$f" --filter pandoc-filter -o rebuild/"${f}".md
done
