#!/usr/bin/env python

from pandocfilters import *
import sys
import json

content = []
def collectCells(key, value, format, meta):
  global content
  if key == 'Para':
    content += [Para(value)]
    return

def dumpCells(key, value, format, meta):
  if key == 'Table':
    return Para([Str('xxx')])

if __name__ == "__main__":
    input_stream = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')
    source = input_stream.read()
    if len(sys.argv) > 1:
        format = sys.argv[1]
    else:
        format = ""
    applyJSONFilters([collectCells], source, format)
    sys.stdout.write(json.dumps({   "pandoc-api-version":[1,23],
            "meta":{},
            "blocks":content}))
        

