#!/usr/bin/env python

from pandocfilters import *
import sys
import json

content = []
def collectCells(key, value, format, meta):
  global content
  if key == 'Table':
    ret = []
    attr, caption, colspecs, tablehead, tablebodies, tablefoot = value
    for body in tablebodies:
        b_attr, b_rowheadcolumns, rows1, rows2 = body
        for row in rows1 + rows2:
            r_attr, cells = row
            for cell in cells:
                c_attr, alignment, row_span, col_span, blocks = cell
                ret += blocks
    return ret

def dumpCells(key, value, format, meta):
  if key == 'Table':
    return Para([Str('xxx')])

if __name__ == "__main__":
    toJSONFilter(collectCells)
