#!/usr/bin/env bash

cd "$(dirname $0)"

generate-md() {
    pandoc -t html -f markdown \
           --standalone --template template.pandoc --toc "$@" \
           --toc-depth 1
}

copy-images() {
    mkdir -p ../images/
    rsync -avu --delete "images/" "../images"
}

generate-md index.md -o ../index.html
generate-md rediscovering-the-roots.md -o ../rediscovering-the-roots.html
generate-md ranwar.md -o ../ranwar.html
copy-images
