#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname $0)"

generate-md() {
    pandoc -t html -f markdown \
           --standalone --template template.pandoc \
           --toc \
           --toc-depth 1 \
           "$@"
}

generate-md-no-figures() {
    pandoc -t html -f markdown-implicit_figures \
           --standalone --template template.pandoc \
           --toc \
           --toc-depth 1 \
           "$@"
}

copy-images() {
    mkdir -p ../images/
    rsync -avu --delete "images/" "../images"
}

build-varsity-circle() {
    slug=the-varsity-circle/1933-01
    mkdir -p "../$slug"
    generate-md-no-figures "$slug/index.md" -o "../$slug/index.html"
    cp "$slug/"*.jpg "../$slug/"
}

build-varsity-circle
generate-md index.md -o ../index.html
generate-md rediscovering-the-roots.md -o ../rediscovering-the-roots.html
generate-md ranwar.md -o ../ranwar.html
copy-images
