#!/usr/bin/env bash

cd "$(dirname $0)"

generate-md() {
    pandoc -t html \
           --standalone --template template.pandoc --toc "$@" \
           --toc-depth 1
}

generate-md index.md -o ../index.html
generate-md rediscovering-the-roots.md -o ../rediscovering-the-roots.html
